server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: main
          uri: lb://main/
          predicates:
            - Path=/rickandmortyapi/**
        - id: character
          uri: lb://character
          predicates:
            - Path=/character/**
        - id: location
          uri: lb://location
          predicates:
            - Path=/location/**