server:
  port: 8080

api:
  character:
    url:   https://rickandmortyapi.com/api/character/
  location:
    url:  https://rickandmortyapi.com/api/location/

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

#server.port=8080
#api.character.url = https://rickandmortyapi.com/api/character/
#api.location.url = https://rickandmortyapi.com/api/location/
#application.name = location

#spring.mvc.throw-exception-if-no-handler-found=true
#spring.web.resources.add-mappings=false